'''
说明：
收银主页的操作
'''
import logging
from common.cxm_desired_caps import desired_caps
from common.elementlibrary import Cashierhomepage
import time

class CashierhomepageView(Cashierhomepage):

    def  homepage(self):
        # logging.info('============Check Paper============')
        # self.check_paper()
        time.sleep(10)
        logging.info('============Click chaiBtn============')
        self.check_chaiBtn()
        logging.info('============Jump Code List Center============')
        self.driver.find_element(*self.tvrightButton).click()
        self.driver.implicitly_wait(10)
        logging.info('============Back to Homepage============')
        self.driver.find_element(*self.tvactionbarBack).click()
        logging.info('============Add Customer============')
        self.driver.find_element(*self.btnaddCustomer).click()
        logging.info('============Enter Customer Name============')
        self.driver.find_element(*self.customerName).send_keys(self.fakename())
        logging.info('============Enter Customer Phone============')
        self.driver.find_element(*self.customerPhone).send_keys(self.fakephone())
        logging.info('============Enter Customer CarNO============')
        self.driver.find_element(*self.carNo).send_keys("群马AE86")
        logging.info('============Saved============')
        self.driver.find_element(*self.customersureBtn).click()
        logging.info('============Mysql verification============')
        self.checkaddcustomer()
        logging.info('============Choose batch ==============')
        self.driver.find_elements(*self.tvTitle)[1].click()
        logging.info('============Choose Custom packaging Product ==============')
        self.driver.find_elements(*self.saleNametv)[0].click()
        logging.info('============Choose quantity==============')
        self.driver.find_elements(*self.layoutextfeeContainer )[0].click()
        logging.info('============Input quantity==============')
        self.driver.find_elements(*self.btnNumber)[4].click()
        logging.info('===========Determine===============')
        self.driver.find_element(*self.tvCommit).click()
        # self.driver.implicitly_wait(10)
        # logging.info('===========Turn on the weighbridge===============')
        # self.driver.find_element(*self.truckweightswitchLayout).click()
        # logging.info('============Choose Bulk packaging Product ==============')
        # self.driver.find_elements(*self.saleNametv)[1].click()
        # logging.info('============Choose quantity==============')
        # self.driver.find_elements(*self.layoutextfeeContainer)[0].click()
        # logging.info('============Input quantity==============')
        # self.driver.find_elements(*self.btnNumber)[4].click()
        # logging.info('============Choose quantity==============')
        # self.driver.find_elements(*self.layoutextfeeContainer)[1].click()
        # logging.info('============Input quantity==============')
        # self.driver.find_elements(*self.btnNumber)[6].click()
        # self.driver.find_elements(*self.btnNumber)[9].click()
        # logging.info('============Choose quantity==============')
        # self.driver.find_elements(*self.layoutextfeeContainer)[3].click()
        # logging.info('============Input quantity==============')
        # self.driver.find_elements(*self.btnNumber)[1].click()
        # logging.info('===========Determine===============')
        # self.driver.find_element(*self.tvCommit).click()
        # logging.info('===========Show user===============')
        # self.driver.find_element(*self.showUser).click()
        # logging.info('===========Select user===============')
        # self.driver.find_elements(*self.tvTitle)[9].click()
        logging.info('===========Add Remark===============')
        self.driver.find_element(*self.layoutRremark).click()
        logging.info('===========Enter Remark===============')
        self.driver.find_element(*self.inputValue).send_keys("自动化测试备注长度测试20个字长度测试。")
        logging.info('===========Saved===============')
        self.driver.find_element(*self.tvSure).click()
        logging.info('===========Add Additional fee===============')
        self.driver.find_element(*self.layoutadditionalFee).click()
        logging.info('===========Enter the amount ===============')
        self.driver.find_element(*self.inputValue).send_keys(100)
        logging.info('===========Saved===============')
        self.driver.find_element(*self.tvSure).click()
        logging.info('===========Sales Order===============')
        self.driver.find_element(*self.cashierchoosedopenOrder).click()
        logging.info('===========Cash register===============')
        self.driver.find_element(*self.btncheckOut).click()
        logging.info('============New customers============')
        self.driver.find_element(*self.layoutaddOrder).click()
        self.driver.find_element(*self.layoutaddOrder).click()
        self.driver.find_element(*self.layoutaddOrder).click()
        logging.info('============Delete customers============')
        self.driver.find_elements(*self.ivDelete)[1].click()
        self.driver.find_elements(*self.ivDelete)[1].click()
        self.driver.find_elements(*self.ivDelete)[1].click()
        logging.info('============Choose batch ==============')
        self.driver.find_elements(*self.tvTitle)[1].click()
        logging.info('============Choose Custom packaging Product ==============')
        self.driver.find_elements(*self.saleNametv)[0].click()
        logging.info('============Choose quantity==============')
        self.driver.find_elements(*self.layoutextfeeContainer)[0].click()
        logging.info('============Input quantity==============')
        self.driver.find_elements(*self.btnNumber)[4].click()
        logging.info('===========Determine===============')
        self.driver.find_element(*self.tvCommit).click()
        logging.info('============New customers============')
        self.driver.find_element(*self.layoutaddOrder).click()
        logging.info('============Delete First customer============')
        self.driver.find_elements(*self.ivDelete)[0].click()
        logging.info('============Confirm Button============')
        self.driver.find_element(*self.confirmButton).click()
        logging.info('============Click on the previous order============')
        self.driver.find_element(*self.tvrightMsg).click()
        # logging.info('===========Turn off the weighbridge===============')
        # self.driver.find_element(*self.truckweightswitchLayout).click()

if __name__ == '__main__':
    driver=desired_caps()
    l=CashierhomepageView(driver)
    l.homepage()
